# Generated by Django 5.2.10 on 2026-01-14 07:20

import django.core.serializers.json
import django_msgspec_field.compat.django
import django_msgspec_field.fields
import msgspec
import tests.conftest
import tests.test_app.models
import typing
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExampleModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "example_field",
                    django_msgspec_field.fields.MsgspecSchemaField(
                        default={"count": 1},
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        schema=tests.test_app.models.ExampleSchema,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SampleForwardRefModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "annotated_field",
                    django_msgspec_field.fields.MsgspecSchemaField(
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        schema=tests.test_app.models.SampleSchema,
                    ),
                ),
                (
                    "field",
                    django_msgspec_field.fields.MsgspecSchemaField(
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        schema=typing.ForwardRef("SampleSchema"),
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SampleModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "sample_field",
                    django_msgspec_field.fields.MsgspecSchemaField(
                        encoder=django.core.serializers.json.DjangoJSONEncoder, schema=tests.conftest.InnerSchema
                    ),
                ),
                (
                    "sample_list",
                    django_msgspec_field.fields.MsgspecSchemaField(
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        schema=django_msgspec_field.compat.django.GenericContainer(list, (tests.conftest.InnerSchema,)),
                    ),
                ),
                (
                    "sample_seq",
                    django_msgspec_field.fields.MsgspecSchemaField(
                        default=list,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        schema=django_msgspec_field.compat.django.GenericContainer(list, (tests.conftest.InnerSchema,)),
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SampleModelAnnotated",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "annotated_field",
                    django_msgspec_field.fields.MsgspecSchemaField(
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        schema=django_msgspec_field.compat.django.GenericContainer(
                            typing.Annotated,
                            (
                                django_msgspec_field.compat.django.GenericContainer(typing.Union, (int, float)),
                                msgspec.Meta(gt=0, title="Annotated Field"),
                            ),
                        ),
                    ),
                ),
                (
                    "annotated_schema",
                    django_msgspec_field.fields.MsgspecSchemaField(
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        schema=django_msgspec_field.compat.django.GenericContainer(
                            typing.Annotated,
                            (
                                django_msgspec_field.compat.django.GenericContainer(typing.Union, (int, float)),
                                msgspec.Meta(gt=0),
                            ),
                        ),
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SampleModelWithRoot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "root_field",
                    django_msgspec_field.fields.MsgspecSchemaField(
                        default=list,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        schema=django_msgspec_field.compat.django.GenericContainer(list, (int,)),
                    ),
                ),
            ],
        ),
    ]
